# Apache License Version 2.0
# Copyright 2022 Xin Huang
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import allel
import gzip
import itertools
import os
import numpy as np
import time
import pandas as pd
from multiprocessing import Process, Queue
from sstar.utils import read_data, py2round, read_mapped_region_file, cal_matchpct

import subprocess
import demes
from scipy.stats import norm, nbinom

#@profile
def cal_match_pct(vcf, ref_ind_file, tgt_ind_file, src_ind_file, anc_allele_file, output, thread, score_file, mapped_region_file):
    """
    Description:
        Calculate matchrates for S* haplotypes in the target population with source genomes.
    Arguments:
        vcf str: Name of the VCF file containing genotypes.
        src_vcf str: Name of the VCF file containing genotypes from source populations.
        ref_ind_file str: Name of the file containing sample information from reference populations.
        tgt_ind_file str: Name of the file containing sample information from target populations.
        src_ind_file str: Name of the file containing sample information from source populations.
        anc_allele_file str: Name of the file containing ancestral allele information.
        output str: Name of the output file.
        thread int: Number of threads.
        score_file str: Name of the file containing S* scores calculated by `s-star score`.
        mapped_region_file str: Name of the BED file containing mapped regions.
    """

    ref_data, ref_samples, tgt_data, tgt_samples, src_data, src_samples = read_data(vcf, ref_ind_file, tgt_ind_file, src_ind_file, anc_allele_file)

    res = []
    chr_names = ref_data.keys()

    mapped_intervals = read_mapped_region_file(mapped_region_file)
    data, windows, samples = _read_score_file(score_file, chr_names, tgt_samples)
    sample_size = len(samples)

    header = 'chrom\tstart\tend\tsample\tmatch_rate\tsrc_sample'

    if thread > 1: thread = min(os.cpu_count()-1, sample_size, thread)    
    res = _cal_tgt_match_pct_manager(data, mapped_intervals, samples, tgt_samples, src_samples, tgt_data, src_data, sample_size, thread)

    with open(output, 'w') as o:
        o.write(header+"\n")
        o.write("\n".join(res)+"\n")

#@profile
def _read_score_file(score_file, chr_names, tgt_samples):
    """
    Description:
        Helper function for reading the file generated by `sstar score`.

    Arguments:
        score_file str: Name of the file containing S* scores generated by `sstar score`.
        chr_names list: List containing names of chromosomes for analysis.
        tgt_samples list: List containing names of samples from the target population for analysis.

    Returns:
        data dict: Dictionary containing S* for analysis.
        windows dict: Dictionary containing windows for analysis.
        header str: Header from the file generated by `sstar score`.
        samples list: List containing names of samples in the target population for analysis.
    """

    data = dict()
    windows = dict()
    for c in chr_names:
        windows[c] = []
    samples = []
    with open(score_file, 'r') as f:
        header = f.readline().rstrip()
        for line in f.readlines():
            line = line.rstrip()
            elements = line.split("\t")
            chr_name = elements[0]
            win_start = elements[1]
            win_end = elements[2]
            sample = elements[3]
            if sample not in tgt_samples: continue
            if elements[6] == 'NA': continue
            if sample not in data.keys(): 
                data[sample] = []
                samples.append(sample)
            data[sample].append(line)
            windows[c].append((int(win_start), int(win_end)))

    return data, windows, samples

def _cal_tgt_match_pct_manager(data, mapped_intervals, samples, tgt_samples, src_samples, tgt_data, src_data, sample_size, thread):
    """
    Description:
        Manager function to calculate match percents in target populations using multiprocessing.

    Arguments:
        data dict: Lines from the output file created by `sstar score`.
        mapped_intervals dict: Dictionary of tuples containing mapped regions across the genome.
        sample list: Sample information for individuals needed to be estimated match percents.
        tgt_samples list: Sample information from target populations.
        src_samples list: Sample information from source populations.
        tgt_data dict: Genotype data from target populations.
        src_data dict: Genotype data from source populations.
        sample_size int: Number of individuals analyzed.
        thread int: Number of threads.

    Returns:
        res list: Match percents for target populations.
    """

    try:
        from pytest_cov.embed import cleanup_on_sigterm
    except ImportError:
        pass
    else:
        cleanup_on_sigterm()

    res = []
    in_queue, out_queue = Queue(), Queue()
    workers = [Process(target=_cal_tgt_match_pct_worker, args=(in_queue, out_queue, mapped_intervals, tgt_data, src_data, src_samples, len(tgt_samples))) for ii in range(thread)]

    for t in samples:
        index = tgt_samples.index(t)
        in_queue.put((index, data[t]))
    
    try:
        for worker in workers:
            worker.start()
        for s in range(sample_size):
            item = out_queue.get()
            if item != '': res.append(item)
        for worker in workers:
            worker.terminate()
    finally:
        for worker in workers:
            worker.join()

    return res

def _cal_tgt_match_pct_worker(in_queue, out_queue, mapped_intervals, tgt_data, src_data, src_samples, sample_size):
    """
    Description:
        Worker function to calculate match percents in target populations.

    Arguments:
        in_queue multiprocessing.Queue: multiprocessing.Queue instance to receive parameters from the manager.
        out_queue multiprocessing.Queue: multiprocessing.Queue instance to send results back to the manager.
        mapped_intervals dict: Dictionary of tuples containing mapped regions across the genome.
        tgt_data dict: Genotype data from target populations.
        src_data dict: Genotype data from source populations.
        src_samples list: List containing sample information for source populations.
        sample_size int: Number of individuals analyzed.
    """

    while True:
        index, data = in_queue.get()
        res = _cal_match_pct_ind(data, index, mapped_intervals, tgt_data, src_data, src_samples, sample_size )
        out_queue.put("\n".join(res))

#@profile
def _cal_match_pct_ind(data, tgt_ind_index, mapped_intervals, tgt_data, src_data, src_samples, sample_size):
    """
    Description:
        Helper function for calculating p-values in individuals.

    Arguments:
        data dict: Dictionary containing S* for analysis.
        tgt_ind_index int: Index of the target individual for analysis.
        mapped_intervals dict: Dictionary of tuples containing mapped regions across the genome.
        tgt_data dict: Genotype data from target populations.
        src_data dict: Genotype data from source populations.
        src_samples list: List of samples from source populations.
        sample_size int: Number of individuals analyzed.

    Returns:
        res list: List containing estimated p-values and other statistics.
    """
    print(data)
    res = []
    for line in data:
        elements = line.split("\t")
        chr_name = elements[0]
        win_start, win_end = elements[1], elements[2]
        sample = elements[3]

        # RB note: none of these values are used, can be commented out
        s_star_snps = elements[-1].split(",")
        s_start, s_end = s_star_snps[0], s_star_snps[-1]
        key1 = win_start+'-'+win_end
        key2 = s_start+'-'+s_end

        for src_ind_index in range(len(src_samples)):
            src_sample = src_samples[src_ind_index]
            hap1_res = cal_matchpct(chr_name, mapped_intervals, tgt_data, src_data, tgt_ind_index, src_ind_index, 0, int(win_start), int(win_end), sample_size)
            hap2_res = cal_matchpct(chr_name, mapped_intervals, tgt_data, src_data, tgt_ind_index, src_ind_index, 1, int(win_start), int(win_end), sample_size)
            
            hap1_match_pct = hap1_res[-1]
            hap2_match_pct = hap2_res[-1]
            hap_match_pct = 'NA'

            if (hap1_match_pct != 'NA') and (hap2_match_pct != 'NA'): hap_match_pct = (hap1_match_pct + hap2_match_pct) / 2

            line = f'{chr_name}\t{win_start}\t{win_end}\t{sample}\t{hap_match_pct}\t{src_sample}'
            res.append(line)
    return res

########################################################
# TEMPORARILY ADDING archaic matchrate simulation code #
########################################################
def get_null_matchrates(model, ms_dir, N0, nsamp, nreps, anc_index, anc_size, tgt_index, tgt_size, mut_rate, rec_rate, seq_len, snp_num_range, output_dir, thread, seeds):
    """
    Description:
        Calculates quantiles of expected S*.

    Arguments:
        model str: Name of file containing the demographic model for simulation.
        ms_dir str: Name of the directory containing the ms program.
        N0 int: N0 used in ms simulation.
        nsamp int: Sample size (haploid) used in ms simulation.
        nreps int: Number of replicates used in ms simulation.
        anc_index int: Index of the ancestral population in the demographic model (start from 1).
        anc_size int: Sample size (haploid) of the ancestral population.
        tgt_index int: Index of the target population in the demographic model (start from 1).
        tgt_size int: Sample size (haploid) of the target population.
        mut_rate float: Mutation rate.
        rec_rate float: Recombination rate.
        seq_len int: Length of simulated sequence.
        snp_num_range list: Range of SNP numbers in ms simulation; the first parameter is the minimum SNP number, the second parameter is the maximum SNP number, the third parameter is the step size.
        output_dir str: Number of the output directory.
        thread int: Number of threads.
        seeds: list: Three random seed numbers used in ms simulation.
    """
    if seeds is not None: np.random.seed(np.sum(seeds))
    output_dir = os.path.abspath(output_dir)
    if os.path.exists(output_dir) is False: subprocess.call(['mkdir', output_dir])
    _generate_mut_rec_combination(N0, nreps, mut_rate, rec_rate, seq_len, output_dir)
    _run_ms_simulation(model, ms_dir, N0, nsamp, nreps, anc_index, anc_size, tgt_index, tgt_size, seq_len, snp_num_range, output_dir, thread, seeds)
    #_summary(output_dir, rec_rate)

def _generate_mut_rec_combination(N0, nreps, mut_rate, rec_rate, seq_len, output_dir):
    """
    Description:
        Helper function to create different combination of mutation rates and recombination rates.

    Arguments:
        N0 int: N0 used in ms simulation.
        nreps int: Number of replicates used in ms simulation.
        mut_rate float: Mutation rate.
        rec_rate float: Recombination rate.
        seq_len int: Length of simulated sequence.
        output_dir str: Name of the output directory.
    """
    scaled_mut_rate = 4*N0*mut_rate*seq_len
    scaled_rec_rate = 4*N0*rec_rate*seq_len
    mut_rate_list = norm.rvs(loc=scaled_mut_rate, scale=0.233, size=nreps)
    rec_rate_list = nbinom.rvs(n=0.5, p=0.5/(0.5+scaled_rec_rate), size=nreps)

    rates = f'{output_dir}/rates.combination'
    with open(rates, 'w') as o:
        for i in range(len(mut_rate_list)):
            if mut_rate_list[i] < 0.001: mut_rate_list[i] = 0.001
            if rec_rate_list[i] < 0.001: rec_rate_list[i] = 0.001
            mut_rate = mut_rate_list[i]
            rec_rate = rec_rate_list[i]
            o.write(f'{mut_rate}\t{rec_rate}\n')

def _run_ms_simulation(model, ms_dir, N0, nsamp, nreps, anc_index, anc_size, tgt_index, tgt_size, seq_len, snp_num_range, output_dir, thread, seeds):
    """
    Description
        Helper function for running ms simulation.

    Arguments:
        model str: Name of file containing the demographic model for simulation.
        ms_dir str: Name of the directory containing the ms program.
        N0 int: N0 used in ms simulation.
        nsamp int: Sample size (haploid) used in ms simulation.
        nreps int: Number of replicates used in ms simulation.
        anc_index int: Index of the ancestral population in the demographic model (start from 1).
        anc_size int: Sample size (haploid) of the ancestral population.
        tgt_index int: Index of the target population in the demographic model (start from 1).
        tgt_size int: Sample size (haploid) of the target population.
        seq_len int: Length of simulated sequence.
        snp_num_range list: Range of SNP numbers in ms simulation; the first parameter is the minimum SNP number, the second parameter is the maximum SNP number, the third parameter is the step size.
        output_dir str: Name of the output directory.
        thread int: Number of threads.
        seeds list: Three random seed numbers used in ms simulation.
    """
    graph = demes.load(model)
    samples = np.zeros(len(graph.demes))
    samples[anc_index-1] = anc_size
    samples[tgt_index-1] = tgt_size
    ms_params = demes.to_ms(graph, N0=N0, samples=samples)
    snp_num_list = np.arange(snp_num_range[0], snp_num_range[1]+snp_num_range[2], snp_num_range[2])
    
    ms_exec = os.path.abspath(ms_dir) + '/ms'
    rates = f'{output_dir}/rates.combination'
    anc_list = f'{output_dir}/sim.anc.list'
    tgt_list = f'{output_dir}/sim.tgt.list'
    anc_size = int(anc_size / 2)
    tgt_size = int(tgt_size / 2)

    if anc_index == tgt_index: raise Exception('The ancestral population should be different from the target population.')
    elif anc_index < tgt_index:
        with open(anc_list, 'w') as o:
            for i in range(anc_size):
                o.write(f'ms_{i}\n')
        with open(tgt_list, 'w') as o:
            for i in range(tgt_size):
                o.write(f'ms_{i+anc_size}\n')
    else:
        with open(anc_list, 'w') as o:
            for i in range(anc_size):
                o.write(f'ms_{i+tgt_size}\n')
        with open(tgt_list, 'w') as o:
            for i in range(tgt_size):
                o.write(f'ms_{i}\n')

    try:
        from pytest_cov.embed import cleanup_on_sigterm
    except ImportError:
        pass
    else:
        cleanup_on_sigterm()

    in_queue, out_queue = Queue(), Queue()
    workers = [Process(target=_run_ms_simulation_worker, args=(in_queue, out_queue, output_dir, rates, ms_exec, nsamp, nreps, seq_len, ms_params, anc_list, tgt_list, seeds)) for ii in range(thread)]
 
    for snp_num in snp_num_list:
        in_queue.put(snp_num)

    try:
        for worker in workers:
            worker.start()
        for snp_num in snp_num_list:
            out_queue.get()
        for worker in workers:
            worker.terminate()
    finally:
        for worker in workers:
            worker.join()

def _run_ms_simulation_worker(in_queue, out_queue, output_dir, rates, ms_exec, nsamp, nreps, seq_len, ms_params, anc_list, tgt_list, seeds):
    """
    Description:
        Worker function for running ms simulation.

    Arguments:
        in_queue multiprocessing.Queue: multiprocessing.Queue instance to receive parameters from the manager.
        out_queue multiprocessing.Queue: multiprocessing.Queue instance to send results back to the manager.
        output_dir str: Name of the output directory.
        rates str: Name of the file containing different combination of mutation rates and recombination rates.
        ms_exec str: Path to the ms program.
        nsamp int: Sample size (haploid) used in ms simulation.
        nreps int: Number of replicates used in ms simulation.
        seq_len int: Length of the simulated sequeuence.
        ms_params list: List of ms parameters.
        anc_list str: Name of the file containing individuals from the ancestral population.
        tgt_list str: Name of the file containing individuals from the target population.
        seeds list: Three random seed numbers used in ms simulation.
    """
    while True:
        snp_num = in_queue.get()
        output_subdir = f'{output_dir}/{snp_num}'
        output_ms = f'{output_subdir}/sim.ms'
        output_vcf = f'{output_subdir}/sim.vcf'
        ms_script = f'{output_subdir}/run_ms.sh'

        if seeds is not None:
            cmd = " ".join(['cat', rates, '|', ms_exec, str(nsamp), str(nreps), '-seeds', " ".join([str(s) for s in seeds]), '-t', 'tbs', '-r', 'tbs', str(seq_len), '-s', str(snp_num), ms_params, '>', output_ms])
        else:
            cmd = " ".join(['cat', rates, '|', ms_exec, str(nsamp), str(nreps), '-t', 'tbs', '-r', 'tbs', str(seq_len), '-s', str(snp_num), ms_params, '>', output_ms])
        
        if os.path.exists(output_subdir) is False: subprocess.call(['mkdir', output_subdir])
        with open(ms_script, 'w') as o:
            o.write(cmd+"\n")
        subprocess.call(['bash', ms_script])

        # Calculate the archaic match rates from the .ms file using the py_cal_match_pct_ind_for_simulation function
        print("ABOUT TO DIRECT PY MATCHRATE")
        start = time.time()
        py_sim_matchrates = py_cal_match_pct_ind_for_simulation(output_ms, snp_num, nsamp, anc_list, tgt_list, ploidy=2)
        print(f"Time taken for direct Python match rate calculation: {time.time() - start:.2f} seconds")

        # Calculate archaic match rates from the .ms file utltimately using Kuhlwilm's utils.cal_matchpct() method
        print("ABOUT TO KUHLWILM PY MATCHRATE")
        start = time.time()
        kuhlwilm_sim_matchrates = cal_match_pct_ind_for_simulation(output_ms, seq_len, nsamp, anc_list, tgt_list, ploidy=2)
        print(f"Time taken for Python match rate calculation: {time.time() - start:.2f} seconds")

        # Output both the py and awk match rates
        with open(output_ms+".matchrates", 'w') as o:
            o.write("direct_py_rate, kuhlwilm_py_rate\n")
            for direct_py_rate, kuhlwilm_py_rate in zip(py_sim_matchrates, kuhlwilm_sim_matchrates):
                o.write(f"{direct_py_rate},{kuhlwilm_py_rate}\n")

        out_queue.put('Finished')

def cal_match_pct_ind_for_simulation(output_ms, seq_len, nsamp, anc_list, tgt_list, ploidy=2):
    """
    Calculate the match percentage for every combination of target individual
    against each source individual from each ms simulation replicate.

    Arguments:
        output_ms str: Name of the ms output file.
        anc_list str: Name of the file containing individuals from the ancestral population.
        tgt_list str: Name of the file containing individuals from the target population.

    Returns:
        null_match_rates list: List containing match percentages for each 
                               simulation and combination of target and source individuals.
    """
    null_match_rates = []

    chr_name = "1" # 
    mapped_intervals = None
    win_start = 0
    win_end = seq_len
    ref_ind_file = None
    anc_allele_file = None

    sample_size = nsamp // ploidy

    for sim_num,vcf in enumerate(_ms2vcfs(output_ms, output_ms+".temp", nsamp, seq_len, ploidy)):
        _, _, tgt_data, tgt_samples, src_data, src_samples = read_data(vcf, ref_ind_file, tgt_list, anc_list, anc_allele_file)

        num_tgt_samples = len(tgt_samples)
        num_src_samples = len(src_samples)

        # Calculate match percentages for each combination of target and source individuals
        for tgt_ind_index, src_ind_index in itertools.product(range(num_tgt_samples), range(num_src_samples)):

            hap1_res = cal_matchpct(chr_name, mapped_intervals, tgt_data, src_data, tgt_ind_index, src_ind_index, 0, int(win_start), int(win_end), sample_size)
            hap2_res = cal_matchpct(chr_name, mapped_intervals, tgt_data, src_data, tgt_ind_index, src_ind_index, 1, int(win_start), int(win_end), sample_size)

            hap1_match_pct = hap1_res[-1]
            hap2_match_pct = hap2_res[-1]

            if (hap1_match_pct != 'NA') and (hap2_match_pct != 'NA'):
                hap_match_pct = (hap1_match_pct + hap2_match_pct) / 2
                null_match_rates.append(hap_match_pct)

    return null_match_rates




def _ms2vcfs(ms_file, vcf_file, nsamp, seq_len, ploidy=2):
    """
    Description:
        Converts ms output file into multiple VCF files, one for each ms replicate.

    Arguments:
        ms_file str: Name of the ms file (input).
        vcf_file str: Name of the VCF file (output).
        nsamp int: Number of haploid genomes.
        seq_len int: Sequence length.
        ploidy int: Ploidy of each individual.
    """
    header = "##fileformat=VCFv4.2\n"
    header += "##FORMAT=<ID=GT,Number=1,Type=String,Description=\"Genotype\">\n"
    header += "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\t" + "\t".join(['ms_' + str(i) for i in range(int(nsamp/ploidy))])

    data = {}

    def _data_to_vcf(vcf_file, data):
        with open(vcf_file, 'w') as o:
            o.write(header+"\n")
        
            for j in range(len(data['pos'])):
                pos = int(seq_len * float(data['pos'][j]))
                genotypes = "".join([data['geno'][k][j] for k in range(len(data['geno']))])
                genotypes = "\t".join([a+'|'+b for a,b in zip(genotypes[0::ploidy],genotypes[1::ploidy])])
                o.write(f"1\t{pos}\t.\tA\tT\t100\tPASS\t.\tGT\t{genotypes}\n")

        return vcf_file


    with open(ms_file, 'r') as f:
        f.readline()
        f.readline()
        for l in f.readlines():
            if l.startswith('//'):
                if data:
                    yield _data_to_vcf(vcf_file, data)

                data = {}
                data['pos'] = []
                data['geno'] = []
            elif l.startswith('positions'):
                data['pos'] = l.rstrip().split(" ")[1:]
            elif l.startswith('0') or l.startswith('1'):
                data['geno'].append(l.rstrip())

    if data:
        yield _data_to_vcf(vcf_file, data)

def py_cal_match_pct_ind_for_simulation(output_ms, snp_num, nsamp, anc_list, tgt_list, ploidy=2):
    """
    Calculate match percentages between target and source individuals from ms simulation output.
    
    Arguments:
        output_ms str: Name of the ms output file.
        snp_num int: Number of SNPs in the simulation.
        nsamp int: Total number of haploid samples.
        anc_list str: Name of the file containing individuals from the ancestral (source) population.
        tgt_list str: Name of the file containing individuals from the target population.
        ploidy int: Ploidy of each individual (default=2).
        
    Returns:
        match_rates list: List of match percentages for each target-source individual combination.
    """
    
    # Read target and source individual indices from files
    with open(anc_list) as f:
        src_inds = [int(line.strip().split("ms_")[1]) for line in f.readlines()]
    
    with open(tgt_list) as f:
        tgt_inds = [int(line.strip().split("ms_")[1]) for line in f.readlines()]
    
    match_rates = []
    
    def _process_simulation_block(genotype_lines):
        """Process a single simulation block and return match rates."""
        sim_match_rates = []
        
        # Parse genotype data for this simulation
        g = {}
        for sample_idx, line in enumerate(genotype_lines):
            g[sample_idx] = line.strip()

        # Calculate match rates for all target-source combinations
        for tgt_ind in tgt_inds:
            for src_ind in src_inds:
                # Get genotypes for both haplotypes
                src_gt_h1 = g[src_ind * 2 + 0]
                src_gt_h2 = g[src_ind * 2 + 1]
                
                hap_match_pct = 0.0
                valid_calculation = True
                
                # Calculate match rate for both target haplotypes
                for ploidy_i in range(2):
                    hap_site_num = 0
                    hap_shared_src_hom_site_num = 0
                    hap_shared_src_het_site_num = 0
                    
                    tgt_gt = g[tgt_ind * 2 + ploidy_i]
                    
                    # Use zip for more pythonic iteration over genotype positions
                    for tgt_allele, src_allele_h1, src_allele_h2 in zip(tgt_gt, src_gt_h1, src_gt_h2):
                        # Check if target or source has variant at this position
                        if tgt_allele == "1" or src_allele_h1 == "1" or src_allele_h2 == "1":
                            hap_site_num += 1
                        
                        # Count shared sites where target has variant
                        if tgt_allele == "1":
                            src_allele_sum = int(src_allele_h1) + int(src_allele_h2)
                            if src_allele_sum == 2:  # Source is homozygous variant
                                hap_shared_src_hom_site_num += 1
                            elif src_allele_sum == 1:  # Source is heterozygous
                                hap_shared_src_het_site_num += 1
                    
                    # Calculate match percentage for this haplotype
                    if hap_site_num > 0:
                        hap_match_src_allele_num = hap_shared_src_hom_site_num + 0.5 * hap_shared_src_het_site_num
                        hap_match_pct += 0.5 * (hap_match_src_allele_num / hap_site_num)
                    else:
                        valid_calculation = False
                        break
                
                # Only add valid match rates
                if valid_calculation:
                    sim_match_rates.append(hap_match_pct)
        
        return sim_match_rates
    
    # Process file in chunks - read line by line instead of loading entire file
    num_init_headers = 2 # minus 1 because of 0-index
    num_per_sim_headers = 5
    num_headers = num_init_headers + num_per_sim_headers
    spacing = nsamp + num_per_sim_headers

    with open(output_ms) as f:
        genotype_lines = []
        for i,line in enumerate(f):
            # Skip initial headers
            if i < num_headers:
                continue
            
            # Collect genotype lines for this simulation block
            if (i - num_headers) % spacing < nsamp:
                genotype_lines.append(line)

            # If we reached the end of a simulation block, process it
            if (i - num_headers) % spacing == nsamp - 1:
                sim_match_rates = _process_simulation_block(genotype_lines)
                match_rates.extend(sim_match_rates)
                genotype_lines = []

    return match_rates