# Apache License Version 2.0
# Copyright 2022 Xin Huang
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import allel
import gzip
import itertools
import os
import numpy as np
import time
import pandas as pd
from multiprocessing import Process, Queue
from sstar.utils import read_data, py2round, read_mapped_region_file, cal_matchpct, calc_segsites_in_window
from dataclasses import dataclass
import logging
import pathlib

import subprocess
import demes
from scipy.stats import norm, nbinom

#@profile
def cal_match_pct(vcf, ref_ind_file, tgt_ind_file, src_ind_file, anc_allele_file, output, thread, score_file, mapped_region_file):
    """
    Description:
        Calculate matchrates for S* haplotypes in the target population with source genomes.
    Arguments:
        vcf str: Name of the VCF file containing genotypes.
        src_vcf str: Name of the VCF file containing genotypes from source populations.
        ref_ind_file str: Name of the file containing sample information from reference populations.
        tgt_ind_file str: Name of the file containing sample information from target populations.
        src_ind_file str: Name of the file containing sample information from source populations.
        anc_allele_file str: Name of the file containing ancestral allele information.
        output str: Name of the output file.
        thread int: Number of threads.
        score_file str: Name of the file containing S* scores calculated by `s-star score`.
        mapped_region_file str: Name of the BED file containing mapped regions.
    """

    ref_data, ref_samples, tgt_data, tgt_samples, src_data, src_samples = read_data(vcf, ref_ind_file, tgt_ind_file, src_ind_file, anc_allele_file)

    res = []
    chr_names = tgt_data.keys()

    mapped_intervals = read_mapped_region_file(mapped_region_file)
    data, windows, samples = _read_score_file(score_file, chr_names, tgt_samples)
    sample_size = len(samples)

    header = 'chrom\tstart\tend\tsample\tmatch_rate\tsrc_sample'

    if thread > 1: thread = min(os.cpu_count()-1, sample_size, thread)    
    res = _cal_tgt_match_pct_manager(data, mapped_intervals, samples, tgt_samples, src_samples, tgt_data, src_data, sample_size, thread)

    with open(output, 'w') as o:
        o.write(header+"\n")
        o.write("\n".join(res)+"\n")

#@profile
def _read_score_file(score_file, chr_names, tgt_samples):
    """
    Description:
        Helper function for reading the file generated by `sstar score`.

    Arguments:
        score_file str: Name of the file containing S* scores generated by `sstar score`.
        chr_names list: List containing names of chromosomes for analysis.
        tgt_samples list: List containing names of samples from the target population for analysis.

    Returns:
        data dict: Dictionary containing S* for analysis.
        windows dict: Dictionary containing windows for analysis.
        header str: Header from the file generated by `sstar score`.
        samples list: List containing names of samples in the target population for analysis.
    """

    data = dict()
    windows = dict()
    for c in chr_names:
        windows[c] = []
    samples = []
    with open(score_file, 'r') as f:
        header = f.readline().rstrip()
        for line in f.readlines():
            line = line.rstrip()
            elements = line.split("\t")
            chr_name = elements[0]
            win_start = elements[1]
            win_end = elements[2]
            sample = elements[3]
            num_snps = elements[6]
            if sample not in tgt_samples: continue
            if num_snps == 'NA': continue

            if sample not in data.keys(): 
                data[sample] = []
                samples.append(sample)
            data[sample].append(line)
            windows[c].append((int(win_start), int(win_end)))

    return data, windows, samples

def _cal_tgt_match_pct_manager(data, mapped_intervals, samples, tgt_samples, src_samples, tgt_data, src_data, sample_size, thread):
    """
    Description:
        Manager function to calculate match percents in target populations using multiprocessing.

    Arguments:
        data dict: Lines from the output file created by `sstar score`.
        mapped_intervals dict: Dictionary of tuples containing mapped regions across the genome.
        sample list: Sample information for individuals needed to be estimated match percents.
        tgt_samples list: Sample information from target populations.
        src_samples list: Sample information from source populations.
        tgt_data dict: Genotype data from target populations.
        src_data dict: Genotype data from source populations.
        sample_size int: Number of individuals analyzed.
        thread int: Number of threads.

    Returns:
        res list: Match percents for target populations.
    """

    try:
        from pytest_cov.embed import cleanup_on_sigterm
    except ImportError:
        pass
    else:
        cleanup_on_sigterm()

    res = []
    in_queue, out_queue = Queue(), Queue()
    workers = [Process(target=_cal_tgt_match_pct_worker, args=(in_queue, out_queue, mapped_intervals, tgt_data, src_data, src_samples, len(tgt_samples))) for ii in range(thread)]

    for t in samples:
        index = tgt_samples.index(t)
        in_queue.put((index, data[t]))
    
    try:
        for worker in workers:
            worker.start()
        for s in range(sample_size):
            item = out_queue.get()
            if item != '': res.append(item)
        for worker in workers:
            worker.terminate()
    finally:
        for worker in workers:
            worker.join()

    return res

def _cal_tgt_match_pct_worker(in_queue, out_queue, mapped_intervals, tgt_data, src_data, src_samples, sample_size):
    """
    Description:
        Worker function to calculate match percents in target populations.

    Arguments:
        in_queue multiprocessing.Queue: multiprocessing.Queue instance to receive parameters from the manager.
        out_queue multiprocessing.Queue: multiprocessing.Queue instance to send results back to the manager.
        mapped_intervals dict: Dictionary of tuples containing mapped regions across the genome.
        tgt_data dict: Genotype data from target populations.
        src_data dict: Genotype data from source populations.
        src_samples list: List containing sample information for source populations.
        sample_size int: Number of individuals analyzed.
    """

    while True:
        index, data = in_queue.get()
        res = _cal_match_pct_ind(data, index, mapped_intervals, tgt_data, src_data, src_samples, sample_size )
        out_queue.put("\n".join(res))

#@profile
def _cal_match_pct_ind(data, tgt_ind_index, mapped_intervals, tgt_data, src_data, src_samples, sample_size):
    """
    Description:
        Helper function for calculating p-values in individuals.

    Arguments:
        data dict: Dictionary containing S* for analysis.
        tgt_ind_index int: Index of the target individual for analysis.
        mapped_intervals dict: Dictionary of tuples containing mapped regions across the genome.
        tgt_data dict: Genotype data from target populations.
        src_data dict: Genotype data from source populations.
        src_samples list: List of samples from source populations.
        sample_size int: Number of individuals analyzed.

    Returns:
        res list: List containing estimated p-values and other statistics.
    """
    res = []
    for line in data:
        elements = line.split("\t")
        chr_name = elements[0]
        win_start, win_end = elements[1], elements[2]
        sample = elements[3]

        # RB note: none of these values are used, can be commented out
        #s_star_snps = elements[-1].split(",")
        #s_start, s_end = s_star_snps[0], s_star_snps[-1]
        #key1 = win_start+'-'+win_end
        #key2 = s_start+'-'+s_end

        for src_ind_index in range(len(src_samples)):
            src_sample = src_samples[src_ind_index]
            hap1_res = cal_matchpct(chr_name, mapped_intervals, tgt_data, src_data, tgt_ind_index, src_ind_index, 0, int(win_start), int(win_end), sample_size)
            hap2_res = cal_matchpct(chr_name, mapped_intervals, tgt_data, src_data, tgt_ind_index, src_ind_index, 1, int(win_start), int(win_end), sample_size)
            
            hap1_match_pct = hap1_res[-1]
            hap2_match_pct = hap2_res[-1]
            hap_match_pct = 'NA'

            if (hap1_match_pct != 'NA') and (hap2_match_pct != 'NA'): hap_match_pct = (hap1_match_pct + hap2_match_pct) / 2

            line = f'{chr_name}\t{win_start}\t{win_end}\t{sample}\t{hap_match_pct}\t{src_sample}'
            res.append(line)
    return res

########################################################
# TEMPORARILY ADDING archaic matchrate simulation code #
########################################################
def archaic_matchrate_pvalue(vcf, threshold_fpath, matchrate_fpath, score_fpath, model, ms_dir, N0, nsamp, nreps, anc_index, anc_size, tgt_index, tgt_size, mut_rate, rec_rate, output_dir, threads, seeds):
    """archaic_matchrate_pvalue: calculate p-values for archaic match rates

    Arguments:
        threshold_fpath str: Path to the file containing significant regions from `sstar threshold`
        matchrate_fpath str: Path to the file containing archaic match rates from `sstar matchrate`
        score_fpath str: Path to the file containing S* scores from `sstar score`
        model str: Path to the Demes demographic model file for simulation
        ms_dir str: Path to the directory containing the `ms` executable
        N0 int: N0 used in ms simulation
        nsamp int: Sample size (haploid) used in ms simulation
        nreps int: Number of replicates used in ms simulation
        anc_index int: Index of the ancestral population in the demographic model (1-based index)
        anc_size int: Sample size (haploid) of the ancestral population
        tgt_index int: Index of the target population in the demographic model (1-based index)
        tgt_size int: Sample size (haploid) of the target population
        mut_rate float: Mutation rate used in ms simulation
        rec_rate float: Recombination rate used in ms simulation
        output_dir str: Directory where the output file will be saved
        threads int: Number of threads to use for the simulation (NOTE only 1 process is used for now)
        seeds list: List of three random seed numbers used in ms simulation


    Output:
        output_dir/archaic_matchrate_pvalues.tsv: A TSV file containing the archaic match rates and their p-values for each significant region.

    Intermediate outputs:
        output_dir/X-SNPs_Y-bp/sim.ms: A directory for each unique region length and SNP number, containing the ms simulation output file.
        output_dir/run_ms.sh: A shell script for running the ms simulation with the specified parameters.
    """
    logging.basicConfig(level=logging.INFO) # NOTE SETUP SOMEWHERE ELSE
    logging.info("Calculating null match rates from simulated data without introgression...")
    logging.info(f"Using threshold file: {threshold_fpath}")
    logging.info(f"Using match rate file: {matchrate_fpath}")
    logging.info(f"Using score file: {score_fpath}")
    logging.info(f"Using demographic model: {model}")
    logging.info(f"Using ms program in directory: {ms_dir}")
    logging.info(f"Using N0: {N0}, sample size: {nsamp}, number of replicates: {nreps}")
    logging.info(f"Ancestral population index: {anc_index}, size: {anc_size}")
    logging.info(f"Target population index: {tgt_index}, size: {tgt_size}")
    logging.info(f"Mutation rate: {mut_rate}, recombination rate: {rec_rate}")
    logging.info(f"Output directory: {output_dir}, threads: {threads}, seeds: {seeds}")

    allel_vcf = allel.read_vcf(vcf)
    snps_per_sample_per_region = {}
    with open(score_fpath) as f:
        f.readline() # Skip header
        for line in f:
            elements = line.strip().split('\t')
            chrom, start, end, sample, _s_star_score, _region_ind_SNP_number, S_star_SNP_number, _S_star_SNPs = elements

            # Look in the original vcf file to count the number of segregating sites in this region
            segsites = calc_segsites_in_window(allel_vcf, chrom, int(start), int(end))

            k = f"{sample}:{chrom}:{start}-{end}"
            if k in snps_per_sample_per_region:
                raise ValueError(f"Duplicate region {k} found in score file {score_fpath}.")

            snps_per_sample_per_region[k] = 650 #segsites #(NOTE for now just hardcoding segsites to be 650 for all regions)

    # Use the output of the `sstar matchrate` command to get the archaic match rates per sample per region
    # here's what the columns of the TSV file look like:
    # chrom	start	end	sample	match_rate	src_sample
    archaic_match_rates = {}
    with open(matchrate_fpath) as f:
        f.readline() # Skip header
        for line in f:
            elements = line.strip().split('\t')
            chrom, start, end, sample, match_rate, src_sample = elements
            k = f"{sample}:{chrom}:{start}-{end}"
            if k in archaic_match_rates:
                raise ValueError(f"Duplicate region {k} found in match rate file {matchrate_fpath}.")

            match_rate = float(match_rate) if match_rate != 'NA' else 0.0
            archaic_match_rates[k] = (match_rate, src_sample)

    # Loop through the significant regions in the output file of `sstar threshold`
    # which has the following columns:
    # chrom	start	end	sample	S*_score	expected_S*_score	local_recomb_rate	quantile	significant
    @dataclass
    class SignificantRegion:
        chrom: str
        start: int
        end: int
        sample: str
        S_star_score: float
        expected_S_star_score: float
        local_recomb_rate: float
        quantile: float
        archaic_match_rate: float
        src_sample: str
        snp_num: int
        match_rate_pvalue: float = None  # Placeholder for p-value, to be calculated later

    significant_regions = []
    with open(threshold_fpath) as f:
        f.readline() # Skip header
        for line in f:
            elements = line.strip().split('\t')
            chrom, start, end, sample, S_star_score, expected_S_star_score, local_recomb_rate, quantile, significant = elements

            k = f"{sample}:{chrom}:{start}-{end}"
            if k not in snps_per_sample_per_region:
                raise ValueError(f"Region {k} not found in `sstar score` output file.")

            if k not in archaic_match_rates:
                raise ValueError(f"Region {k} not found in `sstar matchrate` output file.")
            
            snp_num = snps_per_sample_per_region[k]
            archaic_match_rate, src_sample = archaic_match_rates[k]
            significant_region = SignificantRegion(
                chrom=chrom,
                start=int(start),
                end=int(end),
                sample=sample,
                S_star_score=float(S_star_score),
                expected_S_star_score=float(expected_S_star_score),
                local_recomb_rate=float(local_recomb_rate),
                quantile=float(quantile),
                archaic_match_rate=archaic_match_rate,
                src_sample=src_sample,
                snp_num=snp_num
            )
            significant_regions.append(significant_region)

    # Create a list of unique region-lengths and number of SNPs from the significant_regions
    region_lengths_num_snps = [(r.end - r.start + 1, r.snp_num) for r in significant_regions]
    unique_region_lengths_num_snps = list(set(region_lengths_num_snps))

    logging.info(f"Number of significant regions: {len(significant_regions)}")
    logging.info(f"Number of unique region lengths / SNP numbers to simulate: {len(unique_region_lengths_num_snps)}")

    # For each combination of region length and number of SNPs, run the null match rate simulation
    os.makedirs(output_dir, exist_ok=True)
    output_file = os.path.join(output_dir, 'archaic_matchrate_pvalues.tsv')
    output_f = open(output_file, 'w')
    header = "chrom\tstart\tend\tsample\tS*_score\texpected_S*_score\tlocal_recomb_rate\tquantile\tarchaic_match_rate\tsrc_sample\tsnp_num\tmatch_rate_pvalue"
    output_f.write(header + "\n")
    for region_length, snp_num in unique_region_lengths_num_snps:
        null_matchrates = _get_null_matchrates(
            model=model,
            ms_dir=ms_dir,
            N0=N0,
            nsamp=nsamp,
            nreps=nreps,
            anc_index=anc_index,
            anc_size=anc_size,
            tgt_index=tgt_index,
            tgt_size=tgt_size,
            mut_rate=mut_rate,
            rec_rate=rec_rate,
            seq_len=region_length,
            snp_num_range=(snp_num, snp_num, 1), #start and end are the same, step size is 1 to just get that specific SNP number
            output_dir=output_dir,
            thread=threads,
            seeds=seeds,
        )

        # Determine the number of total SNPs for each

        # NOTE THIS IS STRANGELY SETUP WHERE IT LOOPS THROUGH THE SIGNIFICANT REGIONS
        # NOTE TO SEE WHICH ARE IN THIS NULL MATCHRATE SIMULATION AND THEN CALCULATES THE P-VALUE
        # NOTE REFACTOR THIS LATER BY BASICALLY CHANGING THE LOOP ORDER
        # For each significant region, calculate the p-value based on the null match rates
        # for the corresponding region length and number of SNPs
        for r in significant_regions:
            if r.end - r.start + 1 != region_length:
                continue

            if r.snp_num != snp_num:
                continue

            # Calculate the p-value as the proportion of null match rates that are greater than or equal to the archaic match rate
            p_value = sum(1 for m in null_matchrates if m >= r.archaic_match_rate) / len(null_matchrates)
            r.match_rate_pvalue = p_value

            # Write the significant region with its p-value to the output file
            output_f.write(f"{r.chrom}\t{r.start}\t{r.end}\t{r.sample}\t{r.S_star_score}\t{r.expected_S_star_score}\t{r.local_recomb_rate}\t{r.quantile}\t{r.archaic_match_rate}\t{r.src_sample}\t{r.snp_num}\t{py2round(r.match_rate_pvalue, 6)}\n")

    output_f.close()

def _get_null_matchrates(model, ms_dir, N0, nsamp, nreps, anc_index, anc_size, tgt_index, tgt_size, mut_rate, rec_rate, seq_len, snp_num_range, output_dir, thread, seeds):
    """
    Description:
        Calculates quantiles of expected S*.

    Arguments:
        model str: Name of file containing the demographic model for simulation.
        ms_dir str: Name of the directory containing the ms program.
        N0 int: N0 used in ms simulation.
        nsamp int: Sample size (haploid) used in ms simulation.
        nreps int: Number of replicates used in ms simulation.
        anc_index int: Index of the ancestral population in the demographic model (start from 1).
        anc_size int: Sample size (haploid) of the ancestral population.
        tgt_index int: Index of the target population in the demographic model (start from 1).
        tgt_size int: Sample size (haploid) of the target population.
        mut_rate float: Mutation rate.
        rec_rate float: Recombination rate.
        seq_len int: Length of simulated sequence.
        snp_num_range list: Range of SNP numbers in ms simulation; the first parameter is the minimum SNP number, the second parameter is the maximum SNP number, the third parameter is the step size.
        output_dir str: Number of the output directory.
        thread int: Number of threads.
        seeds: list: Three random seed numbers used in ms simulation.

    Returns:
        null_matchrates list: List of match percentages for each target-source individual combination.
    """
    if seeds is not None: np.random.seed(np.sum(seeds))
    output_dir = os.path.abspath(output_dir)
    if os.path.exists(output_dir) is False: subprocess.call(['mkdir', output_dir])
    _generate_mut_rec_combination(N0, nreps, mut_rate, rec_rate, seq_len, output_dir)
    null_matchrates = _run_ms_simulation(model, ms_dir, N0, nsamp, nreps, anc_index, anc_size, tgt_index, tgt_size, seq_len, snp_num_range, output_dir, thread, seeds)
    return null_matchrates

def _generate_mut_rec_combination(N0, nreps, mut_rate, rec_rate, seq_len, output_dir):
    """
    Description:
        Helper function to create different combination of mutation rates and recombination rates.

    Arguments:
        N0 int: N0 used in ms simulation.
        nreps int: Number of replicates used in ms simulation.
        mut_rate float: Mutation rate.
        rec_rate float: Recombination rate.
        seq_len int: Length of simulated sequence.
        output_dir str: Name of the output directory.
    """
    scaled_mut_rate = 4*N0*mut_rate*seq_len
    scaled_rec_rate = 4*N0*rec_rate*seq_len
    mut_rate_list = norm.rvs(loc=scaled_mut_rate, scale=0.233, size=nreps)     # For each simulation, draw a random mutation rate centered around the scaled mutation rate
    rec_rate_list = nbinom.rvs(n=0.5, p=0.5/(0.5+scaled_rec_rate), size=nreps) # For each simulation, draw a random recombination rate from a negative binomial distribution centered around the scaled recombination rate

    rates = f'{output_dir}/rates.combination'
    with open(rates, 'w') as o:
        for i in range(len(mut_rate_list)):
            if mut_rate_list[i] < 0.001: mut_rate_list[i] = 0.001
            if rec_rate_list[i] < 0.001: rec_rate_list[i] = 0.001
            mut_rate = mut_rate_list[i]
            rec_rate = rec_rate_list[i]
            o.write(f'{mut_rate}\t{rec_rate}\n')

def _run_ms_simulation(model, ms_dir, N0, nsamp, nreps, anc_index, anc_size, tgt_index, tgt_size, seq_len, snp_num_range, output_dir, thread, seeds):
    """
    Description
        Helper function for running ms simulation.

    Arguments:
        model str: Name of file containing the demographic model for simulation.
        ms_dir str: Name of the directory containing the ms program.
        N0 int: N0 used in ms simulation.
        nsamp int: Sample size (haploid) used in ms simulation.
        nreps int: Number of replicates used in ms simulation.
        anc_index int: Index of the ancestral population in the demographic model (start from 1).
        anc_size int: Sample size (haploid) of the ancestral population.
        tgt_index int: Index of the target population in the demographic model (start from 1).
        tgt_size int: Sample size (haploid) of the target population.
        seq_len int: Length of simulated sequence.
        snp_num_range list: Range of SNP numbers in ms simulation; the first parameter is the minimum SNP number, the second parameter is the maximum SNP number, the third parameter is the step size.
        output_dir str: Name of the output directory.
        thread int: Number of threads.
        seeds list: Three random seed numbers used in ms simulation.

    Returns:
        sim_archaic_matchrates list: List of match percentages for each target-source individual combination.
    """
    graph = demes.load(model)
    samples = np.zeros(len(graph.demes))
    samples[anc_index-1] = anc_size
    samples[tgt_index-1] = tgt_size
    ms_params = demes.to_ms(graph, N0=N0, samples=samples)
    snp_num_list = np.arange(snp_num_range[0], snp_num_range[1]+snp_num_range[2], snp_num_range[2])
    
    ms_exec = os.path.abspath(ms_dir) + '/ms'
    rates = f'{output_dir}/rates.combination'
    anc_list = f'{output_dir}/sim.anc.list'
    tgt_list = f'{output_dir}/sim.tgt.list'
    anc_size = int(anc_size / 2)
    tgt_size = int(tgt_size / 2)

    if anc_index == tgt_index: raise Exception('The ancestral population should be different from the target population.')
    elif anc_index < tgt_index:
        with open(anc_list, 'w') as o:
            for i in range(anc_size):
                o.write(f'ms_{i}\n')
        with open(tgt_list, 'w') as o:
            for i in range(tgt_size):
                o.write(f'ms_{i+anc_size}\n')
    else:
        with open(anc_list, 'w') as o:
            for i in range(anc_size):
                o.write(f'ms_{i+tgt_size}\n')
        with open(tgt_list, 'w') as o:
            for i in range(tgt_size):
                o.write(f'ms_{i}\n')

    try:
        from pytest_cov.embed import cleanup_on_sigterm
    except ImportError:
        pass
    else:
        cleanup_on_sigterm()

    in_queue, out_queue = Queue(), Queue()
    workers = [Process(target=_run_ms_simulation_worker, args=(in_queue, out_queue, output_dir, rates, ms_exec, nsamp, nreps, seq_len, ms_params, anc_list, tgt_list, seeds)) for ii in range(thread)]
 
    for snp_num in snp_num_list:
        in_queue.put(snp_num)

    # NOTE THE CODE BELOW ONLY RUNS ONCE, IT'S NOT USING MULTIPROCESSING
    ms_output_paths = []
    try:
        for worker in workers:
            worker.start()
        for snp_num in snp_num_list:
            ms_output_paths.append(out_queue.get())
        for worker in workers:
            worker.terminate()
    finally:
        for worker in workers:
            worker.join()

    # Calculate the archaic match rates from the .ms file
    sim_archaic_matchrates = py_cal_match_pct_ind_for_simulation(ms_output_paths[0], nsamp, anc_list, tgt_list, ploidy=2)
    return sim_archaic_matchrates

def _run_ms_simulation_worker(in_queue, out_queue, output_dir, rates, ms_exec, nsamp, nreps, seq_len, ms_params, anc_list, tgt_list, seeds):
    """
    Description:
        Worker function for running ms simulation.

    Arguments:
        in_queue multiprocessing.Queue: multiprocessing.Queue instance to receive parameters from the manager.
        out_queue multiprocessing.Queue: multiprocessing.Queue instance to send results back to the manager.
        output_dir str: Name of the output directory.
        rates str: Name of the file containing different combination of mutation rates and recombination rates.
        ms_exec str: Path to the ms program.
        nsamp int: Sample size (haploid) used in ms simulation.
        nreps int: Number of replicates used in ms simulation.
        seq_len int: Length of the simulated sequeuence.
        ms_params list: List of ms parameters.
        anc_list str: Name of the file containing individuals from the ancestral population.
        tgt_list str: Name of the file containing individuals from the target population.
        seeds list: Three random seed numbers used in ms simulation.
    """
    while True:
        snp_num = in_queue.get()
        output_subdir = f'{output_dir}/{snp_num}-SNPs_{seq_len}-bp'
        output_ms = f'{output_subdir}/sim.ms'
        ms_script = f'{output_subdir}/run_ms.sh'

        if seeds is not None:
            cmd = " ".join(['cat', rates, '|', ms_exec, str(nsamp), str(nreps), '-seeds', " ".join([str(s) for s in seeds]), '-t', 'tbs', '-r', 'tbs', str(seq_len), '-s', str(snp_num), ms_params, '>', output_ms])
        else:
            cmd = " ".join(['cat', rates, '|', ms_exec, str(nsamp), str(nreps), '-t', 'tbs', '-r', 'tbs', str(seq_len), '-s', str(snp_num), ms_params, '>', output_ms])
        
        if os.path.exists(output_subdir) is False: subprocess.call(['mkdir', output_subdir])
        with open(ms_script, 'w') as o:
            o.write(cmd+"\n")
        subprocess.call(['bash', ms_script])

        out_queue.put(output_ms)


def py_cal_match_pct_ind_for_simulation(output_ms, nsamp, anc_list, tgt_list, ploidy=2):
    """
    Calculate match percentages between target and source individuals from ms simulation output.
    
    Arguments:
        output_ms str: Name of the ms output file.
        snp_num int: Number of SNPs in the simulation.
        nsamp int: Total number of haploid samples.
        anc_list str: Name of the file containing individuals from the ancestral (source) population.
        tgt_list str: Name of the file containing individuals from the target population.
        ploidy int: Ploidy of each individual (default=2).
        
    Returns:
        match_rates list: List of match percentages for each target-source individual combination.
    """
    
    # Read target and source individual indices from files
    with open(anc_list) as f:
        src_inds = [int(line.strip().split("ms_")[1]) for line in f.readlines()]
    
    with open(tgt_list) as f:
        tgt_inds = [int(line.strip().split("ms_")[1]) for line in f.readlines()]
    
    match_rates = []
    
    def _process_simulation_block(genotype_lines):
        """Process a single simulation block and return match rates."""
        sim_match_rates = []
        
        # Parse genotype data for this simulation
        g = {}
        for sample_idx, line in enumerate(genotype_lines):
            g[sample_idx] = line.strip()

        # Calculate match rates for all target-source combinations
        for tgt_ind in tgt_inds:
            for src_ind in src_inds:
                # Get genotypes for both haplotypes
                src_gt_h1 = g[src_ind * 2 + 0]
                src_gt_h2 = g[src_ind * 2 + 1]
                
                hap_match_pct = 0.0
                valid_calculation = True
                
                # Calculate match rate for both target haplotypes
                for ploidy_i in range(2):
                    hap_site_num = 0
                    hap_shared_src_hom_site_num = 0
                    hap_shared_src_het_site_num = 0
                    
                    tgt_gt = g[tgt_ind * 2 + ploidy_i]
                    
                    # Use zip for more pythonic iteration over genotype positions
                    for tgt_allele, src_allele_h1, src_allele_h2 in zip(tgt_gt, src_gt_h1, src_gt_h2):
                        # Check if target or source has variant at this position
                        if tgt_allele == "1" or src_allele_h1 == "1" or src_allele_h2 == "1":
                            hap_site_num += 1
                        
                        # Count shared sites where target has variant
                        if tgt_allele == "1":
                            src_allele_sum = int(src_allele_h1) + int(src_allele_h2)
                            if src_allele_sum == 2:  # Source is homozygous variant
                                hap_shared_src_hom_site_num += 1
                            elif src_allele_sum == 1:  # Source is heterozygous
                                hap_shared_src_het_site_num += 1
                    
                    # Calculate match percentage for this haplotype
                    if hap_site_num > 0:
                        hap_match_src_allele_num = hap_shared_src_hom_site_num + 0.5 * hap_shared_src_het_site_num
                        hap_match_pct += 0.5 * (hap_match_src_allele_num / hap_site_num)
                    else:
                        valid_calculation = False
                        break
                
                # Only add valid match rates
                if valid_calculation:
                    sim_match_rates.append(hap_match_pct)
        
        return sim_match_rates
    
    # Process file in chunks - read line by line instead of loading entire file
    num_init_headers = 2 # minus 1 because of 0-index
    num_per_sim_headers = 5
    num_headers = num_init_headers + num_per_sim_headers
    spacing = nsamp + num_per_sim_headers

    with open(output_ms) as f:
        genotype_lines = []
        for i,line in enumerate(f):
            # Skip initial headers
            if i < num_headers:
                continue
            
            # Collect genotype lines for this simulation block
            if (i - num_headers) % spacing < nsamp:
                genotype_lines.append(line)

            # If we reached the end of a simulation block, process it
            if (i - num_headers) % spacing == nsamp - 1:
                sim_match_rates = _process_simulation_block(genotype_lines)
                match_rates.extend(sim_match_rates)
                genotype_lines = []

    return match_rates