# Apache License Version 2.0
# Copyright 2022 Xin Huang
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import allel
import gzip
import itertools
import os
import numpy as np
import time
import pandas as pd
from multiprocessing import Process, Queue, Pool
from sstar.utils import read_data, py2round, read_mapped_region_file, cal_matchpct, calc_segsites_in_window
from dataclasses import dataclass
import logging
import pathlib

from sstar.simulate import MSPrimeSimulator
from sstar.cal_s_star import cal_s_star

import subprocess
import demes
from scipy.stats import norm, nbinom

#@profile
def cal_match_pct(vcf, ref_ind_file, tgt_ind_file, src_ind_file, anc_allele_file, output, thread, score_file, mapped_region_file):
    """
    Description:
        Calculate matchrates for S* haplotypes in the target population with source genomes.
    Arguments:
        vcf str: Name of the VCF file containing genotypes.
        src_vcf str: Name of the VCF file containing genotypes from source populations.
        ref_ind_file str: Name of the file containing sample information from reference populations.
        tgt_ind_file str: Name of the file containing sample information from target populations.
        src_ind_file str: Name of the file containing sample information from source populations.
        anc_allele_file str: Name of the file containing ancestral allele information.
        output str: Name of the output file.
        thread int: Number of threads.
        score_file str: Name of the file containing S* scores calculated by `s-star score`.
        mapped_region_file str: Name of the BED file containing mapped regions.
    """

    ref_data, ref_samples, tgt_data, tgt_samples, src_data, src_samples = read_data(vcf, ref_ind_file, tgt_ind_file, src_ind_file, anc_allele_file)

    res = []
    chr_names = tgt_data.keys()

    mapped_intervals = read_mapped_region_file(mapped_region_file)
    data, windows, samples = _read_score_file(score_file, chr_names, tgt_samples)
    sample_size = len(samples)

    header = 'chrom\tstart\tend\tsample\tmatch_rate\tsrc_sample'

    if thread > 1: thread = min(os.cpu_count()-1, sample_size, thread)    
    res = _cal_tgt_match_pct_manager(data, mapped_intervals, samples, tgt_samples, src_samples, tgt_data, src_data, sample_size, thread)

    with open(output, 'w') as o:
        o.write(header+"\n")
        o.write("\n".join(res)+"\n")

#@profile
def _read_score_file(score_file, chr_names, tgt_samples):
    """
    Description:
        Helper function for reading the file generated by `sstar score`.

    Arguments:
        score_file str: Name of the file containing S* scores generated by `sstar score`.
        chr_names list: List containing names of chromosomes for analysis.
        tgt_samples list: List containing names of samples from the target population for analysis.

    Returns:
        data dict: Dictionary containing S* for analysis.
        windows dict: Dictionary containing windows for analysis.
        header str: Header from the file generated by `sstar score`.
        samples list: List containing names of samples in the target population for analysis.
    """

    data = dict()
    windows = dict()
    for c in chr_names:
        windows[c] = []
    samples = []
    with open(score_file, 'r') as f:
        header = f.readline().rstrip()
        for line in f.readlines():
            line = line.rstrip()
            elements = line.split("\t")
            chr_name = elements[0]
            win_start = elements[1]
            win_end = elements[2]
            sample = elements[3]
            num_snps = elements[6]
            if sample not in tgt_samples: continue
            if num_snps == 'NA': continue

            if sample not in data.keys(): 
                data[sample] = []
                samples.append(sample)
            data[sample].append(line)
            windows[c].append((int(win_start), int(win_end)))

    return data, windows, samples

def _cal_tgt_match_pct_manager(data, mapped_intervals, samples, tgt_samples, src_samples, tgt_data, src_data, sample_size, thread):
    """
    Description:
        Manager function to calculate match percents in target populations using multiprocessing.

    Arguments:
        data dict: Lines from the output file created by `sstar score`.
        mapped_intervals dict: Dictionary of tuples containing mapped regions across the genome.
        sample list: Sample information for individuals needed to be estimated match percents.
        tgt_samples list: Sample information from target populations.
        src_samples list: Sample information from source populations.
        tgt_data dict: Genotype data from target populations.
        src_data dict: Genotype data from source populations.
        sample_size int: Number of individuals analyzed.
        thread int: Number of threads.

    Returns:
        res list: Match percents for target populations.
    """

    try:
        from pytest_cov.embed import cleanup_on_sigterm
    except ImportError:
        pass
    else:
        cleanup_on_sigterm()

    res = []
    in_queue, out_queue = Queue(), Queue()
    workers = [Process(target=_cal_tgt_match_pct_worker, args=(in_queue, out_queue, mapped_intervals, tgt_data, src_data, src_samples, len(tgt_samples))) for ii in range(thread)]

    for t in samples:
        index = tgt_samples.index(t)
        in_queue.put((index, data[t]))
    
    try:
        for worker in workers:
            worker.start()
        for s in range(sample_size):
            item = out_queue.get()
            if item != '': res.append(item)
        for worker in workers:
            worker.terminate()
    finally:
        for worker in workers:
            worker.join()

    return res

def _cal_tgt_match_pct_worker(in_queue, out_queue, mapped_intervals, tgt_data, src_data, src_samples, sample_size):
    """
    Description:
        Worker function to calculate match percents in target populations.

    Arguments:
        in_queue multiprocessing.Queue: multiprocessing.Queue instance to receive parameters from the manager.
        out_queue multiprocessing.Queue: multiprocessing.Queue instance to send results back to the manager.
        mapped_intervals dict: Dictionary of tuples containing mapped regions across the genome.
        tgt_data dict: Genotype data from target populations.
        src_data dict: Genotype data from source populations.
        src_samples list: List containing sample information for source populations.
        sample_size int: Number of individuals analyzed.
    """

    while True:
        index, data = in_queue.get()
        res = _cal_match_pct_ind(data, index, mapped_intervals, tgt_data, src_data, src_samples, sample_size )
        out_queue.put("\n".join(res))

#@profile
def _cal_match_pct_ind(data, tgt_ind_index, mapped_intervals, tgt_data, src_data, src_samples, sample_size):
    """
    Description:
        Helper function for calculating p-values in individuals.

    Arguments:
        data dict: Dictionary containing S* for analysis.
        tgt_ind_index int: Index of the target individual for analysis.
        mapped_intervals dict: Dictionary of tuples containing mapped regions across the genome.
        tgt_data dict: Genotype data from target populations.
        src_data dict: Genotype data from source populations.
        src_samples list: List of samples from source populations.
        sample_size int: Number of individuals analyzed.

    Returns:
        res list: List containing estimated p-values and other statistics.
    """
    res = []
    for line in data:
        elements = line.split("\t")
        chr_name = elements[0]
        win_start, win_end = elements[1], elements[2]
        sample = elements[3]

        # RB note: none of these values are used, can be commented out
        #s_star_snps = elements[-1].split(",")
        #s_start, s_end = s_star_snps[0], s_star_snps[-1]
        #key1 = win_start+'-'+win_end
        #key2 = s_start+'-'+s_end

        for src_ind_index in range(len(src_samples)):
            src_sample = src_samples[src_ind_index]
            hap1_res = cal_matchpct(chr_name, mapped_intervals, tgt_data, src_data, tgt_ind_index, src_ind_index, 0, int(win_start), int(win_end), sample_size)
            hap2_res = cal_matchpct(chr_name, mapped_intervals, tgt_data, src_data, tgt_ind_index, src_ind_index, 1, int(win_start), int(win_end), sample_size)
            
            hap1_match_pct = hap1_res[-1]
            hap2_match_pct = hap2_res[-1]
            hap_match_pct = 'NA'

            if (hap1_match_pct != 'NA') and (hap2_match_pct != 'NA'): hap_match_pct = (hap1_match_pct + hap2_match_pct) / 2

            line = f'{chr_name}\t{win_start}\t{win_end}\t{sample}\t{hap_match_pct}\t{src_sample}'
            res.append(line)
    return res

########################################################
# TEMPORARILY ADDING archaic matchrate simulation code #
########################################################
def archaic_matchrate_pvalue(*,
                             demes_file: pathlib.Path,
                             obs_matchrate_path: pathlib.Path, 
                             output_dir: pathlib.Path,
                             num_sims: int,
                             ref_pop: str,
                             tgt_pop: str,
                             src_pop: str,
                             ref_size: int,
                             tgt_size: int,
                             src_size: int,
                             src_sample_gen: int,
                             mut_rate: float,
                             rec_rate: float,
                             seq_length: int,
                             threads: int,
                             ):
    """archaic_matchrate_pvalue: calculate p-values for archaic match rates

    Performs the following steps once per simulation:
    1) Simulate genetic data without introgression using msprime based on a given demes file
    2) Calculate scores
    3) Calculate match rates

    Then combine the results from all simulations to calculate p-values for observed match rates.
    """
    # NOTE SETUP LOGGING SOMEWHERE ELSE
    logging.basicConfig(
        format='%(asctime)s - %(levelname)s - %(message)s',
        level=logging.INFO,
    )

    logging.info("Calculating null match rates from simulated data without introgression...")
    logging.info(f"Using observed match rate file: {obs_matchrate_path}")
    logging.info(f"Using demographic file: {demes_file}")
    logging.info(f"Using number of simulations: {num_sims}")
    logging.info(f"Reference population: {ref_pop}, size: {ref_size}")
    logging.info(f"Target population: {tgt_pop}, size: {tgt_size}")
    logging.info(f"Source population: {src_pop}, size: {src_size}, sampled {src_sample_gen} generations ago")
    logging.info(f"Mutation rate: {mut_rate}, recombination rate: {rec_rate}")
    logging.info(f"Output directory: {output_dir}, threads: {threads}")

    # Create output directory if it doesn't exist
    output_dir.mkdir(parents=True, exist_ok=True)

    # Create an MSPrimeSimulator instance and define samples and parameters
    msprime_simulator = MSPrimeSimulator(demes_file=demes_file)
    msprime_simulator.define_sample(role="ref", population=ref_pop, num_samples=ref_size)
    msprime_simulator.define_sample(role="tgt", population=tgt_pop, num_samples=tgt_size)
    msprime_simulator.define_sample(role="nean_src", population=src_pop, num_samples=src_size, time=src_sample_gen)
    msprime_simulator.define_params(mut_rate=mut_rate, recomb_rate=rec_rate, seq_length=seq_length)

    # Run simulations with a multiprocessing pool
    with Pool(processes=min(threads, os.cpu_count()-1)) as p:
        p.starmap(
            _run_sstar_sim_vcf,
            [(msprime_simulator, output_dir, sim_num) for sim_num in range(num_sims)]
        )


    # TODO Run score calculations with a multiprocessing pool

    # TODO Run match rate calculations with a multiprocessing pool

    # TODO Read all matchrate results and calculate p-values for observed match rates


def _run_sstar_sim_vcf(simulator: MSPrimeSimulator, out_simulation_dir: pathlib.Path, sim_num: int) -> pathlib.Path:
    """Run msprime simulation and save VCF and sample lists to the specified directory.

    Parameters:
        simulator (MSPrimeSimulator): An instance of the MSPrimeSimulator class with defined samples and parameters.
        out_simulation_dir (pathlib.Path): Directory to save the output files.
    """
    if simulator.ts is not None:
        raise RuntimeError("Simulation already run. Please create a new MSPrimeSimulator instance for a new simulation.")

    out_simulation_dir.mkdir(parents=True, exist_ok=True)
    out_simulation_dir = out_simulation_dir / f"sim{sim_num}"
    out_simulation_dir.mkdir(parents=True, exist_ok=True)

    simulator.simulate()
    simulator.save(out_simulation_dir)

    return out_simulation_dir / "sim_input.vcf" #TODO change hardcoded name later


#TODO, use this function later
#def _run_sstar_score():
#    cal_s_star(
#        vcf=vcf_path,
#        ref_ind_file=ref_ind_file,
#        tgt_ind_file=tgt_ind_file,
#        anc_allele_file=anc_allele_file,
#        output=score_output,
#        window_size=window_size,
#        step_size=step_size,
#        min_snp=min_snp,
#        threads=threads,
#    )
#    pass