name: build

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Add micromamba to system path
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-name: sstar-build
        environment-file: build-env.yml

    - name: Test with pytest
      run: |
        export R_LIBS=${CONDA_PREFIX}/lib/R/library
        micromamba run -n sstar-build pytest --cov=. --cov-report term-missing
        micromamba run -n sstar-build coverage xml
